name: mediminder
description: "A smart medicine reminder app for elderly people and busy adults."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  flutter_tts: ^4.0.2
  intl: ^0.19.0
  # Image Selection
  image_picker: ^1.1.2
  # Gemini AI (Assisted OCR)
  google_generative_ai: ^0.4.5
  # Legacy OCR Fallback
  google_mlkit_text_recognition: ^0.13.0
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
